CREATE TABLE amazon_products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    price DECIMAL(10,2),
    rating INTEGER CONSTRAINT chk_rating CHECK (rating >= 0 AND rating <= 5),
    img_link TEXT,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);