CREATE TABLE amazon_orders (
    order_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES amazon_users(user_id) ON DELETE CASCADE NOT NULL,
    -- product_Id INTEGER REFERENCES amazon_products(id) ON DELETE CASCADE NOT NULL,
    product_Id TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);